### ISSUE TITLE
Проверка лабораторной работы №1

### ISSUE THREAD

**Issue by MrGorky** [MrGorky/L1#1]
Работу выполнила:
*Драганчук Алена Сергеевна

To:@evgeny-p

**Comment by evgeny-p** [comment]
1. Суть лабораторной работы была в поэтапной разработке функционала в отдельной ветке. Каждый коммит должен содержать минимальную порцию изменений с соответствующим текстом в заголовке коммита. Сейчас репозиторий состоит из двух коммитов, возможно, выполненных через веб-интерфейс. Нужно:
    1. Выполнить откат изменений в ветке master. Обращение изменений последнего коммита выполняется командой `git revert HEAD`.
    1. Создать новую ветку и в ней проделать поэтапную разработку приложения.
    1. Слить отдельную ветку в master с ключом `--no-ff`.

    В текущем состоянии работа демонстрирует ошибку, о которой было сказано на первом занятии: есть результат, но отсутствует процесс.

1. Заголовок задачи и название репозитория не соответствуют действительности: по факту сдается лабораторная работа №2.

1. Файл с исходным кодом содержит пробелы и не содержит расширения. Как следствие:

    1. Исходник не распознается компилятором, что приводит к ошибке компиляции: `File format not recognized`.
    1. Формат исходника не распознается гитхабом: при просмотре через [веб-интерфейс](https://github.com/MrGorky/L1/blob/1fa9d9a872c37657c7bc66adfb536f76eca756be/Quadratic%20equation) отсутствует подсветка синтаксиса.

1. Полная копипаста работы одногруппника: https://github.com/DX37/QuadraticEquation.

1. В тексте задачи маркер ненумерованного списка не отделен пробелом от имени, и поэтому отображается как звездочка.
